  pch.cpp
  dllmain.cpp
C:\Users\Professional\source\repos\DLLforChallenge\dllmain.cpp(25,1): warning C4273: firstExercise: несовместимое связывание dll
C:\Users\Professional\source\repos\DLLforChallenge\DLLforChallenge.h(9,37): message : см. предыдущее определение "firstExercise"
C:\Users\Professional\source\repos\DLLforChallenge\dllmain.cpp(30,1): warning C4273: secondExercise: несовместимое связывание dll
C:\Users\Professional\source\repos\DLLforChallenge\DLLforChallenge.h(10,37): message : см. предыдущее определение "secondExercise"
C:\Users\Professional\source\repos\DLLforChallenge\dllmain.cpp(36,1): warning C4273: thirdExercise: несовместимое связывание dll
C:\Users\Professional\source\repos\DLLforChallenge\DLLforChallenge.h(11,37): message : см. предыдущее определение "thirdExercise"
     Создается библиотека C:\Users\Professional\source\repos\DLLforChallenge\Debug\DLLforChallenge.lib и объект C:\Users\Professional\source\repos\DLLforChallenge\Debug\DLLforChallenge.exp
  DLLforChallenge.vcxproj -> C:\Users\Professional\source\repos\DLLforChallenge\Debug\DLLforChallenge.dll
